### ISSUE TITLE
Check if Location is enabled otherwise scan returns no results

### ISSUE THREAD

**Issue by TxtSync** [tripflex/WifiWizard2#44]
### Issue type
Select all that apply
- [X] Bug
- [ ] Enhancement
- [ ] Task
- [ ] Question
- [ ] Other

### Description

When using the Scan method I get symbol true and value is an empty array. If I try startScan and getScanResults I get the same problem. If I use listNetworks and I connected manually I can see it in the list. I have tried the permissions method and I get "PERMISSION_GRANTED"

**Expected behavior:** 

Return a list of about 15 WiFi Networks

**Actual behavior:** 

No networks

**Reproduces how often:** 

Happens every time

### Versions

Ionic - 3.20.0
NPM - 3.10.8
Android 6

**Comment by SentleAngular** [comment]
`07-16 15:36:26.320   837  1062 D WifiStateMachine: starting scan for "SENTLE.CO.UK"-WPA_PSK with 2432
07-16 15:36:26.321 21081 21081 D wpa_supplicant: wlan0: Control interface command 'SCAN TYPE=ONLY freq=2432'
07-16 15:36:26.321 21081 21081 D wpa_supplicant: wlan0: Setting scan request: 0.000000 sec
07-16 15:36:26.321 21081 21081 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=3
07-16 15:36:26.321 21081 21081 D wpa_supplicant: wlan0: Starting AP scan for wildcard SSID
07-16 15:36:26.321 21081 21081 D wpa_supplicant: wlan0: Limit manual scan to specified channels
07-16 15:36:26.321 21081 21081 D wpa_supplicant: wlan0: Add radio work 'scan'@0xb7492e10
07-16 15:36:26.321 21081 21081 D wpa_supplicant: wlan0: First radio work item in the queue - schedule start immediately
07-16 15:36:26.322 21081 21081 D wpa_supplicant: wlan0: Starting radio work 'scan'@0xb7492e10 after 0.000108 second wait
07-16 15:36:26.322 21081 21081 D wpa_supplicant: wlan0: nl80211: scan request
07-16 15:36:26.322 21081 21081 D wpa_supplicant: nl80211: Scan SSID - hexdump(len=0): [NULL]
07-16 15:36:26.322 21081 21081 D wpa_supplicant: nl80211: Scan extra IEs - hexdump(len=18): 7f 06 00 00 0a 82 01 40 6b 01 0f dd 05 50 6f 9a 10 10
07-16 15:36:26.322 21081 21081 D wpa_supplicant: nl80211: Scan frequency 2432 MHz
07-16 15:36:26.335 21081 21081 D wpa_supplicant: Scan requested (ret=0) - scan timeout 30 seconds
07-16 15:36:26.336 21081 21081 D wpa_supplicant: nl80211: Event message available
07-16 15:36:26.336 21081 21081 D wpa_supplicant: nl80211: Drv Event 33 (NL80211_CMD_TRIGGER_SCAN) received for wlan0
07-16 15:36:26.336 21081 21081 D wpa_supplicant: wlan0: nl80211: Scan trigger
07-16 15:36:26.336 21081 21081 D wpa_supplicant: wlan0: Event SCAN_STARTED (47) received
07-16 15:36:26.336 21081 21081 D wpa_supplicant: wlan0: Own scan request started a scan in 0.000282 seconds
07-16 15:36:26.336 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=0 send_len=24
07-16 15:36:26.336 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_330-6\x00
07-16 15:36:26.336 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=448 send_len=24
07-16 15:36:26.336 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_837-7\x00
07-16 15:36:26.410 21081 21081 D wpa_supplicant: nl80211: Event message available
07-16 15:36:26.410 21081 21081 D wpa_supplicant: nl80211: Drv Event 34 (NL80211_CMD_NEW_SCAN_RESULTS) received for wlan0
07-16 15:36:26.410 21081 21081 D wpa_supplicant: wlan0: nl80211: New scan results available
07-16 15:36:26.410 21081 21081 D wpa_supplicant: nl80211: Scan included frequencies: 2432
07-16 15:36:26.410 21081 21081 D wpa_supplicant: wlan0: Event SCAN_RESULTS (3) received
07-16 15:36:26.410 21081 21081 D wpa_supplicant: wlan0: Scan completed in 0.074238 seconds
07-16 15:36:26.410 21081 21081 D wpa_supplicant: nl80211: Associated on 2432 MHz
07-16 15:36:26.410 21081 21081 D wpa_supplicant: nl80211: Associated with 9c:5c:8e:b5:ba:38
07-16 15:36:26.410 21081 21081 D wpa_supplicant: nl80211: Received scan results (8 BSSes)
07-16 15:36:26.411 21081 21081 D wpa_supplicant: nl80211: Scan results indicate BSS status with 9c:5c:8e:b5:ba:38 as associated
07-16 15:36:26.411 21081 21081 D wpa_supplicant: wlan0: BSS: Start scan result update 88
07-16 15:36:26.415 21081 21081 D wpa_supplicant: BSS: last_scan_res_used=8/32
07-16 15:36:26.416 21081 21081 D wpa_supplicant: wlan0: Scan-only results received
07-16 15:36:26.416 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=0 send_len=24
07-16 15:36:26.416 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_330-6\x00
07-16 15:36:26.416 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=448 send_len=24
07-16 15:36:26.416 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_837-7\x00
07-16 15:36:26.416 21081 21081 D wpa_supplicant: wlan0: Radio work 'scan'@0xb7492e10 done in 0.094424 seconds
07-16 15:36:26.416   432   542 W XTCC-5.1.0.13: [WifiScanner] WiFi scan result : [1] AP's
07-16 15:36:26.418 21081 21081 D wpa_supplicant: wlan0: Control interface command 'SCAN_RESULTS'
07-16 15:36:26.419 21081 21081 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=1303
07-16 15:36:26.420 21081 21081 D wpa_supplicant: wlan0: Control interface command 'SCAN_RESULTS'
07-16 15:36:26.422 21081 21081 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=1303
07-16 15:36:26.430 21081 21081 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=3510
07-16 15:36:26.436 21081 21081 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=3922
07-16 15:36:26.441 21081 21081 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=2848
07-16 15:36:26.453 21081 21081 D wpa_supplicant: EAPOL: EAP Session-Id not available
07-16 15:36:26.453 21081 21081 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=274
07-16 15:36:28.015 21081 21081 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
07-16 15:36:28.027 21081 21081 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=48
07-16 15:36:30.042  1110  1110 D NetworkController.WifiSignalController: Change in state from: connected=true,enabled=true,level=4,inetCondition=1,iconGroup=IconGroup(Wi-Fi Icons),activityIn=false,activityOut=false,rssi=-46,lastModified=07-16 03:36:26,ssid="SEN
TLE.CO.UK"
07-16 15:36:30.042  1110  1110 D NetworkController.WifiSignalController:        to: connected=true,enabled=true,level=4,inetCondition=1,iconGroup=IconGroup(Wi-Fi Icons),activityIn=true,activityOut=false,rssi=-46,lastModified=07-16 03:36:26,ssid="SENTLE.CO.UK"
07-16 15:36:31.031 21081 21081 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
07-16 15:36:31.043 21081 21081 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=48
07-16 15:36:32.478 22467 22542 D WifiWizard2: WifiWizard2: verifyWifiEnabled entered.
07-16 15:36:32.479 22467 22542 V WifiWizard2: Entering startScan
07-16 15:36:32.479 22467 22542 V WifiWizard2: Submitting timeout to threadpool
07-16 15:36:32.479 22467 22542 V WifiWizard2: Registering broadcastReceiver
07-16 15:36:32.480 22467 26950 V WifiWizard2: Entering timeout
07-16 15:36:32.482 22467 22542 V WifiWizard2: Starting wifi scan
07-16 15:36:32.486 21081 21081 D wpa_supplicant: wlan0: Control interface command 'SCAN TYPE=ONLY'
07-16 15:36:32.486 21081 21081 D wpa_supplicant: wlan0: Setting scan request: 0.000000 sec
07-16 15:36:32.486 21081 21081 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=3
07-16 15:36:32.486 21081 21081 D wpa_supplicant: wlan0: Starting AP scan for wildcard SSID
07-16 15:36:32.486 21081 21081 D wpa_supplicant: wlan0: Add radio work 'scan'@0xb7492e10
07-16 15:36:32.486 21081 21081 D wpa_supplicant: wlan0: First radio work item in the queue - schedule start immediately
07-16 15:36:32.486 21081 21081 D wpa_supplicant: wlan0: Starting radio work 'scan'@0xb7492e10 after 0.000100 second wait
07-16 15:36:32.486 21081 21081 D wpa_supplicant: wlan0: nl80211: scan request
07-16 15:36:32.487 21081 21081 D wpa_supplicant: nl80211: Scan SSID - hexdump(len=0): [NULL]
07-16 15:36:32.487 21081 21081 D wpa_supplicant: nl80211: Scan extra IEs - hexdump(len=18): 7f 06 00 00 0a 82 01 40 6b 01 0f dd 05 50 6f 9a 10 10
07-16 15:36:32.491 21081 21081 D wpa_supplicant: Scan requested (ret=0) - scan timeout 30 seconds
07-16 15:36:32.491 21081 21081 D wpa_supplicant: nl80211: Event message available
07-16 15:36:32.491 21081 21081 D wpa_supplicant: nl80211: Drv Event 33 (NL80211_CMD_TRIGGER_SCAN) received for wlan0
07-16 15:36:32.491 21081 21081 D wpa_supplicant: wlan0: nl80211: Scan trigger
07-16 15:36:32.491 21081 21081 D wpa_supplicant: wlan0: Event SCAN_STARTED (47) received
07-16 15:36:32.491 21081 21081 D wpa_supplicant: wlan0: Own scan request started a scan in 0.000278 seconds
07-16 15:36:32.491 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=0 send_len=24
07-16 15:36:32.491 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_330-6\x00
07-16 15:36:32.491 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=448 send_len=24
07-16 15:36:32.492 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_837-7\x00
07-16 15:36:33.079 21081 21081 D wpa_supplicant: nl80211: Event message available
07-16 15:36:33.079 21081 21081 D wpa_supplicant: nl80211: Drv Event 34 (NL80211_CMD_NEW_SCAN_RESULTS) received for wlan0
07-16 15:36:33.079 21081 21081 D wpa_supplicant: wlan0: nl80211: New scan results available
07-16 15:36:33.079 21081 21081 D wpa_supplicant: nl80211: Scan included frequencies: 2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462 2467 2472
07-16 15:36:33.079 21081 21081 D wpa_supplicant: wlan0: Event SCAN_RESULTS (3) received
07-16 15:36:33.079 21081 21081 D wpa_supplicant: wlan0: Scan completed in 0.588416 seconds
07-16 15:36:33.080 21081 21081 D wpa_supplicant: nl80211: Associated on 2432 MHz
07-16 15:36:33.080 21081 21081 D wpa_supplicant: nl80211: Associated with 9c:5c:8e:b5:ba:38
07-16 15:36:33.080 21081 21081 D wpa_supplicant: nl80211: Received scan results (10 BSSes)
07-16 15:36:33.080 21081 21081 D wpa_supplicant: nl80211: Scan results indicate BSS status with 9c:5c:8e:b5:ba:38 as associated
07-16 15:36:33.080 21081 21081 D wpa_supplicant: wlan0: BSS: Start scan result update 89
07-16 15:36:33.080 21081 21081 D wpa_supplicant: wlan0: BSS: Add new id 80 BSSID 74:ea:3a:dd:17:4c SSID 'HDDLTD'
07-16 15:36:33.080 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=0 send_len=41
07-16 15:36:33.081 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_330-6\x00
07-16 15:36:33.081 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=448 send_len=41
07-16 15:36:33.081 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_837-7\x00
07-16 15:36:33.081 21081 21081 D wpa_supplicant: wlan0: BSS: Remove id 73 BSSID d2:05:c2:53:7b:f9 SSID 'Virgin Media' due to no match in scan
07-16 15:36:33.081 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=896 send_len=43
07-16 15:36:33.081 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_330-6\x00
07-16 15:36:33.081 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=1344 send_len=43
07-16 15:36:33.081 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_837-7\x00
07-16 15:36:33.081 21081 21081 D wpa_supplicant: wlan0: BSS: Remove id 46 BSSID c0:05:c2:53:7b:f9 SSID 'VM8962766' due to no match in scan
07-16 15:36:33.081 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=1792 send_len=43
07-16 15:36:33.081 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_330-6\x00
07-16 15:36:33.081 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=2240 send_len=43
07-16 15:36:33.082 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_837-7\x00
07-16 15:36:33.082 21081 21081 D wpa_supplicant: wlan0: BSS: Remove id 74 BSSID 40:0d:10:ac:ee:d1 SSID 'VM7864167' due to no match in scan
07-16 15:36:33.082 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=2688 send_len=43
07-16 15:36:33.082 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_330-6\x00
07-16 15:36:33.082 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=3136 send_len=43
07-16 15:36:33.082 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_837-7\x00
07-16 15:36:33.082 21081 21081 D wpa_supplicant: wlan0: BSS: Remove id 3 BSSID 00:18:4d:e0:85:24 SSID 'TREC' due to no match in scan
07-16 15:36:33.082 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=3584 send_len=42
07-16 15:36:33.082 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_330-6\x00
07-16 15:36:33.082 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=4032 send_len=42
07-16 15:36:33.082 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_837-7\x00
07-16 15:36:33.084 21081 21081 D wpa_supplicant: wlan0: BSS: Remove id 75 BSSID 52:0d:10:ac:ee:d1 SSID 'Virgin Media' due to no match in scan
07-16 15:36:33.084 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=0 send_len=43
07-16 15:36:33.085 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_330-6\x00
07-16 15:36:33.085 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=448 send_len=43
07-16 15:36:33.085 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_837-7\x00
07-16 15:36:33.085 21081 21081 D wpa_supplicant: wlan0: BSS: Remove id 67 BSSID 52:0d:10:bb:a9:41 SSID 'Virgin Media' due to no match in scan
07-16 15:36:33.085 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=896 send_len=43
07-16 15:36:33.085 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_330-6\x00
07-16 15:36:33.085 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=1344 send_len=43
07-16 15:36:33.085 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_837-7\x00
07-16 15:36:33.085 21081 21081 D wpa_supplicant: wlan0: BSS: Remove id 72 BSSID aa:a1:98:55:87:8b SSID 'kian ' due to no match in scan
07-16 15:36:33.085 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=1792 send_len=43
07-16 15:36:33.085 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_330-6\x00
07-16 15:36:33.085 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=2240 send_len=43
07-16 15:36:33.085 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_837-7\x00
07-16 15:36:33.086 21081 21081 D wpa_supplicant: wlan0: BSS: Remove id 77 BSSID 02:84:b0:dd:3c:2c SSID 'BTWi-fi' due to no match in scan
07-16 15:36:33.086 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=2688 send_len=43
07-16 15:36:33.086 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_330-6\x00
07-16 15:36:33.086 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=3136 send_len=43
07-16 15:36:33.086 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_837-7\x00
07-16 15:36:33.086 21081 21081 D wpa_supplicant: BSS: last_scan_res_used=10/32
07-16 15:36:33.086 21081 21081 D wpa_supplicant: wlan0: Scan-only results received
07-16 15:36:33.086 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=3584 send_len=24
07-16 15:36:33.086 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_330-6\x00
07-16 15:36:33.086 21081 21081 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=4032 send_len=24
07-16 15:36:33.086 21081 21081 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_837-7\x00
07-16 15:36:33.086 21081 21081 D wpa_supplicant: wlan0: Radio work 'scan'@0xb7492e10 done in 0.599876 seconds
07-16 15:36:33.093 21081 21081 D wpa_supplicant: wlan0: Control interface command 'SCAN_RESULTS'
07-16 15:36:33.094 21081 21081 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=848
07-16 15:36:33.098 21081 21081 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=3705
07-16 15:36:33.098   432   542 W XTCC-5.1.0.13: [WifiScanner] WiFi scan result : [7] AP's
07-16 15:36:33.100 21081 21081 D wpa_supplicant: wlan0: Control interface command 'SCAN_RESULTS'
07-16 15:36:33.101 21081 21081 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=848
07-16 15:36:33.105 21081 21081 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=2733
07-16 15:36:33.115 21081 21081 D wpa_supplicant: EAPOL: EAP Session-Id not available
07-16 15:36:33.115 21081 21081 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=274
07-16 15:36:33.119 22467 22467 V WifiWizard2: Entering onReceive
07-16 15:36:33.122 22467 22467 V WifiWizard2: In onReceive, success
07-16 15:36:33.122   837  2739 D PowerManagerService: getScreenOffTimeoutLocked: mIsCurrentTest = false
07-16 15:36:33.125   837  1137 D WifiService: acquireWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@e25f370}
07-16 15:36:33.129   837  1528 D WifiService: releaseWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@e25f370}
07-16 15:36:33.131   837  2577 D PowerManagerService: getScreenOffTimeoutLocked: mIsCurrentTest = false
07-16 15:36:33.133   837  1503 D PowerManagerService: getScreenOffTimeoutLocked: mIsCurrentTest = false
07-16 15:36:33.137  8108  8811 W ctxmgr  : [AclManager]null policy map (1) 57, clientInfo=(accnt=account#-517948760#, com.google.android.gms(10012):IndoorOutdoorProducer, vrsn=12685000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 8108)
07-16 15:36:33.140  8108  8811 W ctxmgr  : [AclManager]null policy map (2) 57, clientInfo=(accnt=account#-517948760#, com.google.android.gms(10012):IndoorOutdoorProducer, vrsn=12685000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 8108)
07-16 15:36:33.144  8108  8811 W ctxmgr  : [AclManager]null policy map (1) 57, clientInfo=(accnt=account#-517948760#, com.google.android.gms(10012):IndoorOutdoorProducer, vrsn=12685000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 8108)
07-16 15:36:33.155   837  2576 D PowerManagerService: getScreenOffTimeoutLocked: mIsCurrentTest = false
07-16 15:36:34.047 21081 21081 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
07-16 15:36:34.059 21081 21081 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=48
`

**Comment by SentleAngular** [comment]
Found the root cause

`07-16 15:46:44.050  2918  2918 W System.err:    at org.json.JSON.typeMismatch(JSON.java:100)
07-16 15:46:44.050  2918  2918 W System.err:    at org.json.JSONArray.getJSONObject(JSONArray.java:525)
07-16 15:46:44.050  2918  2918 W System.err:    at wifiwizard2.WifiWizard2.getScanResults(WifiWizard2.java:913)
07-16 15:46:44.050  2918  2918 W System.err:    at wifiwizard2.WifiWizard2.access$200(WifiWizard2.java:57)
07-16 15:46:44.050  2918  2918 W System.err:    at wifiwizard2.WifiWizard2$1.onReceive(WifiWizard2.java:279)
07-16 15:46:44.050  2918  2918 W System.err:    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:881)
07-16 15:46:44.050  2918  2918 W System.err:    at android.os.Handler.handleCallback(Handler.java:739)
07-16 15:46:44.050  2918  2918 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)
07-16 15:46:44.050  2918  2918 W System.err:    at android.os.Looper.loop(Looper.java:148)
07-16 15:46:44.050  2918  2918 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:5417)
07-16 15:46:44.050  2918  2918 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
07-16 15:46:44.050  2918  2918 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-16 15:46:44.050  2918  2918 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by SentleAngular** [comment]
So this issue was Options not being provided however still no response for WiFi networks

**Comment by tripflex** [comment]
@SentleAngular what do you mean by that?  Can you please elaborate so I can try and help you with this?

**Comment by tripflex** [comment]
@SentleAngular thank you will look at adding this for the next release

https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/android/Diagnostic_Location.java#L151

**Comment by tripflex** [comment]
@TxtSync so i've added some handling for this in the 3.2.0 to-be-released branch under `location` which i will merge into `dev` here shortly
